import adamPicture from '../images/IMG_1226.jpeg';
import backPicture from '../images/IMG_1395.jpeg';

const activeMembers = [
    {
        id: 11,
        name: 'Alex Thompson',
        position: 'Intramural Coordinator',
        major: 'Mechanical Engineering',
        class: "'25",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '300',
    },
    {
        id: 12,
        name: 'Emma Garcia',
        position: 'Merchandise Chair',
        major: 'Industrial Engineering',
        class: "'26",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '301',
    },
    {
        id: 13,
        name: 'Ryan Murphy',
        position: null,
        major: 'Computer Science',
        class: "'24",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '302',
    },
    {
        id: 14,
        name: 'Isabella Kim',
        position: 'Alumni Relations',
        major: 'Electrical Engineering',
        class: "'25",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '303',
    },
    {
        id: 15,
        name: 'Ethan Brown',
        position: null,
        major: 'Civil Engineering',
        class: "'26",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '304',
    },
    {
        id: 16,
        name: 'Ava Wilson',
        position: 'Fundraising Chair',
        major: 'Biomedical Engineering',
        class: "'24",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '305',
    },
    {
        id: 17,
        name: 'Noah Davis',
        position: 'Web Master',
        major: 'Software Engineering',
        class: "'25",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '306',
    },
    {
        id: 18,
        name: 'Sophia Martinez',
        position: null,
        major: 'Chemical Engineering',
        class: "'26",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '307',
    },
    {
        id: 19,
        name: 'Liam Johnson',
        position: 'Historian',
        major: 'Aerospace Engineering',
        class: "'24",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '308',
    },
    {
        id: 20,
        name: 'Mia Taylor',
        position: 'Academic Chair',
        major: 'Environmental Engineering',
        class: "'25",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '309',
    },
];

export default activeMembers;