import adamPicture from '../images/IMG_1226.jpeg';
import backPicture from '../images/IMG_1395.jpeg';

const alumniMembers = [
    {
        id: 21,
        name: 'Jennifer Lee',
        major: 'Electrical Engineering',
        graduated: 2020,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Embrace challenges, they're opportunities in disguise.",
        pinNumber: '250',
    },
    {
        id: 22,
        name: 'Christopher Wong',
        major: 'Mechanical Engineering',
        graduated: 2019,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Your Theta Tau network is your greatest professional asset.",
        pinNumber: '251',
    },
    {
        id: 23,
        name: 'Amanda Chen',
        major: 'Computer Science',
        graduated: 2021,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Never stop learning, the industry is always evolving.",
        pinNumber: '252',
    },
    {
        id: 24,
        name: 'Robert Johnson',
        major: 'Civil Engineering',
        graduated: 2018,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Leadership in Theta Tau translates directly to career success.",
        pinNumber: '253',
    },
    {
        id: 25,
        name: 'Michelle Patel',
        major: 'Chemical Engineering',
        graduated: 2020,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Your Theta Tau brothers will be lifelong friends and mentors.",
        pinNumber: '254',
    },
    {
        id: 26,
        name: 'Brian Nguyen',
        major: 'Aerospace Engineering',
        graduated: 2019,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Dream big and work hard, success will follow.",
        pinNumber: '255',
    },
    {
        id: 27,
        name: 'Jessica Martinez',
        major: 'Industrial Engineering',
        graduated: 2021,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Networking is key, start building relationships now.",
        pinNumber: '256',
    },
    {
        id: 28,
        name: 'Kevin Smith',
        major: 'Biomedical Engineering',
        graduated: 2018,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Take risks and embrace failure, it's the best teacher.",
        pinNumber: '257',
    },
    {
        id: 29,
        name: 'Sarah Davis',
        major: 'Environmental Engineering',
        graduated: 2020,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Use your skills to make a positive impact on the world.",
        pinNumber: '258',
    },
    {
        id: 30,
        name: 'Thomas Wilson',
        major: 'Software Engineering',
        graduated: 2019,
        frontImage: adamPicture,
        backImage: backPicture,
        backMessage: "Stay curious and never stop asking questions.",
        pinNumber: '259',
    },
];

export default alumniMembers;