import adamPicture from '../images/IMG_1226.jpeg';
import backPicture from '../images/IMG_1395.jpeg';

const eboardMembers = [
    {
        id: 1,
        name: 'Adam Vick',
        position: 'Regent',
        major: 'Computer Engineering',
        class: "'24",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '290',
    },
    {
        id: 2,
        name: 'Emily Johnson',
        position: 'Vice Regent',
        major: 'Electrical Engineering',
        class: "'25",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '291',
    },
    {
        id: 3,
        name: 'Michael Chen',
        position: 'Treasurer',
        major: 'Mechanical Engineering',
        class: "'24",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '292',
    },
    {
        id: 4,
        name: 'Sarah Martinez',
        position: 'Secretary',
        major: 'Civil Engineering',
        class: "'26",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '293',
    },
    {
        id: 5,
        name: 'David Kim',
        position: 'Pledge Educator',
        major: 'Aerospace Engineering',
        class: "'25",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '294',
    },
    {
        id: 6,
        name: 'Rachel Lee',
        position: 'Professional Development',
        major: 'Chemical Engineering',
        class: "'24",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '295',
    },
    {
        id: 7,
        name: 'Jason Taylor',
        position: 'Rush Chair',
        major: 'Industrial Engineering',
        class: "'25",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '296',
    },
    {
        id: 8,
        name: 'Sophia Patel',
        position: 'Social Chair',
        major: 'Biomedical Engineering',
        class: "'24",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '297',
    },
    {
        id: 9,
        name: 'Daniel Rodriguez',
        position: 'Brotherhood Chair',
        major: 'Software Engineering',
        class: "'26",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '298',
    },
    {
        id: 10,
        name: 'Olivia Wilson',
        position: 'Service Chair',
        major: 'Environmental Engineering',
        class: "'25",
        frontImage: adamPicture,
        backImage: backPicture,
        pinNumber: '299',
    },
];

export default eboardMembers;